// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt3kFIHUMRuz19hMhrkffR3TC52MfEIak',
    appId: '1:750268120139:web:4a173611e5e44d99b8e1ce',
    messagingSenderId: '750268120139',
    projectId: 'vaagaiapp-92a96',
    authDomain: 'vaagaiapp-92a96.firebaseapp.com',
    databaseURL: 'https://vaagaiapp-92a96-default-rtdb.firebaseio.com',
    storageBucket: 'vaagaiapp-92a96.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2yJitDBTMqRTTMQjPdK_WEkF8gqiUG7k',
    appId: '1:750268120139:android:2713fe351eda29f2b8e1ce',
    messagingSenderId: '750268120139',
    projectId: 'vaagaiapp-92a96',
    databaseURL: 'https://vaagaiapp-92a96-default-rtdb.firebaseio.com',
    storageBucket: 'vaagaiapp-92a96.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDt3kFIHUMRuz19hMhrkffR3TC52MfEIak',
    appId: '1:750268120139:web:4a173611e5e44d99b8e1ce',
    messagingSenderId: '750268120139',
    projectId: 'vaagaiapp-92a96',
    authDomain: 'vaagaiapp-92a96.firebaseapp.com',
    databaseURL: 'https://vaagaiapp-92a96-default-rtdb.firebaseio.com',
    storageBucket: 'vaagaiapp-92a96.firebasestorage.app',
  );

}