// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiVOm8vLowMun-Ax4OHGPoVy4NSIQE87Y',
    appId: '1:974007969277:web:240abcdf902008f31d6594',
    messagingSenderId: '974007969277',
    projectId: 'vaagaiapp-3c760',
    authDomain: 'vaagaiapp-3c760.firebaseapp.com',
    storageBucket: 'vaagaiapp-3c760.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARrYaygcKMEQoCpMQfvTNbZwjhlXxxrms',
    appId: '1:974007969277:android:d65f0332f3fb70231d6594',
    messagingSenderId: '974007969277',
    projectId: 'vaagaiapp-3c760',
    storageBucket: 'vaagaiapp-3c760.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiVOm8vLowMun-Ax4OHGPoVy4NSIQE87Y',
    appId: '1:974007969277:web:1417e04916066d3e1d6594',
    messagingSenderId: '974007969277',
    projectId: 'vaagaiapp-3c760',
    authDomain: 'vaagaiapp-3c760.firebaseapp.com',
    storageBucket: 'vaagaiapp-3c760.firebasestorage.app',
  );
}
